### ISSUE TITLE
Add workout item

### ISSUE THREAD

**Issue by chrisstonedev** [GymRatTrax/GymRatTrax-Scheduler#1]
_From @christopher-stone on March 9, 2015 16:39_

Add ability to create a new schedule into which to put new workouts.

_Copied from original issue: wford7/AndroidStudio#1_

**Comment by chrisstonedev** [comment]
_From @awrigh36 on March 20, 2015 15:50_

Task switched to implement add/edit workouts base feature. Schedule is no longer an object.

**Comment by chrisstonedev** [comment]
Code nearly complete. Issue rolling over to Sprint 2.

**Comment by chrisstonedev** [comment]
Code nearly complete. Issue rolling over to Sprint 3.

**Comment by chrisstonedev** [comment]
Nearly complete. Rolling over to Sprint 4.

**Comment by chrisstonedev** [comment]
Rolling over to Sprint 5.

**Comment by awrigh36** [comment]
Code complete. Testing ongoing.
