### ISSUE TITLE
Prevent exceptions in Progress Reports -> Weight Graph

### ISSUE THREAD

**Issue by wford7** [GymRatTrax/GymRatTrax-Scheduler#52]
If weight has not been recorded for the current day, a Null Exception will be raised.  Work-around for now will be to add a dialogue box so users may update their weight.

**Comment by chrisstonedev** [comment]
If the problem is that the most recent day has not had a weight recording, I can augment the database method to add an extra weight value for the Date value equal to the "to" Date passed in. I'll look at it and report back.

**Comment by chrisstonedev** [comment]
After getting weight data from the database, if null was returned or we have at most one data point (which is not supported in the ViewGraph line graph), a toast is displayed and the graph area remains blank.
