### ISSUE TITLE
Change exercise name biking to cycling 

### ISSUE THREAD

**Issue by awrigh36** [GymRatTrax/GymRatTrax-Scheduler#53]
Cycling works better when interacting google calendar api and possibly future fitness app integration.

**Comment by chrisstonedev** [comment]
I'll take care of this. It should be a fairly easy fix. In order to minimize the work needed, though, please do not add a Biking workout in your test dataset unless you are okay with clearing data later. If this were found later on, I would trigger a database update to match the new name.

**Comment by chrisstonedev** [comment]
Completed.
