### ISSUE TITLE
Add date picker to Profile Setup

### ISSUE THREAD

**Issue by chrisstonedev** [GymRatTrax/GymRatTrax-Scheduler#56]
The profile setup input for birth date should be easier to input.

This is a direct user suggestion.

**Comment by chrisstonedev** [comment]
Due to prioritizing data and activity errors found in 0.9.0.1, this and #57 will be pushed until 0.9.2 (unless it happens to be ready soon). These features are nice but not necessary before 1.0.0.

**Comment by awrigh36** [comment]
I've implemented the datepicker dialogs for the setup profile and edit profile activities. Number pickers for weight, height, bf% will be added very soon.

**Comment by chrisstonedev** [comment]
@awrigh36 All right, cool. If you feel confident enough in the date pickers, I'll test them tonight and make sure they're in for 0.9.1 and we'll save the other pickers for 0.9.2.

I wasn't trying to rush anything; I just realized how bad the other errors were and wanted those patched quickly.

**Comment by awrigh36** [comment]
@christopher-stone sounds good, I'm making some minor cosmetic changes and the date picker dialog will be ready by tonight.

**Comment by chrisstonedev** [comment]
Passes testing. I added a bit more code to handle the international date format (only affects what is displayed in the EditText). This will be going out in 0.9.1 today.
