### ISSUE TITLE
Synchronization with Google Calendar

### ISSUE THREAD

**Issue by chrisstonedev** [GymRatTrax/GymRatTrax-Scheduler#9]
_From @christopher-stone on March 9, 2015 16:43_

Routines can be synchronized with Google Calendar using relevant APIs to make events more visible and more flexible.

_Copied from original issue: wford7/AndroidStudio#9_

**Comment by chrisstonedev** [comment]
Rolling over to Sprint 3.

**Comment by chrisstonedev** [comment]
Nearly complete. Rolling over to Sprint 4.

**Comment by chrisstonedev** [comment]
Rolling over to Sprint 5.

**Comment by chrisstonedev** [comment]
About to be checked in. Rolling over to Sprint 6.

**Comment by chrisstonedev** [comment]
Testing due by Thursday. Rolling over to Sprint 7, but it must be ready by Thursday's beta/demo.

**Comment by awrigh36** [comment]
Completed, checked in, and testing is nearly done.
